# Generated by Django 5.0.6 on 2024-06-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
